# Specify version format
version: "0.0.{build}"

# Operating system (build VM template)
os: Visual Studio 2015
 
# build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
platform:
  - Win32
  - x64

# build configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

# clone directory
clone_folder: C:\Projects\ReinsCoreWotlk\Source\

# branches to build
branches:
  # whitelist
  only:
    - master

# Do not build on tags (GitHub only)
skip_tags: true

# scripts to run before build
before_build:
  - md build && cd build
  - echo Running cmake...
  - cmake -G"Visual Studio 14 Win64" -DTOOLS=False -DCMAKE_CXX_FLAGS=" /DWIN32 /D_WINDOWS /W3 /GR /EHsc /WX" -DCMAKE_C_FLAGS="/DWIN32 /D_WINDOWS /W3 /WX"

# unit test
test: off

artifacts:
  - path: bin\$(platform)_$(configuration)
    name: $(APPVEYOR_PROJECT_NAME)_$(platform)_$(configuration)
